### ISSUE TITLE
python manage.py apidoc  error

### ISSUE THREAD

**Issue by allran** [viniciuschiele/flask-apidoc#3]
```

Last login: Sat Jul 16 11:54:16 on ttys000
allranMacPro:~ allran$ /Users/allran/PycharmProjects/college/flask/bin/python /Users/allran/PycharmProjects/college/manage.py apidoc
Traceback (most recent call last):
  File "/Users/allran/PycharmProjects/college/manage.py", line 93, in <module>
    manager.run()
  File "/Users/allran/PycharmProjects/college/flask/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/allran/PycharmProjects/college/flask/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/allran/PycharmProjects/college/flask/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/allran/PycharmProjects/college/flask/lib/python2.7/site-packages/flask_apidoc/commands.py", line 43, in run
    return subprocess.call(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by viniciuschiele** [comment]
You have to install the apidoc, take a look at their page, www.apidocjs.com

**Comment by allran** [comment]
Thank you @viniciuschiele .  I have successfull install the apidoc and generate the ApiDoc files at 'static/docs'. There is one problem that when i load 'http://localhost:5000/docs/', result 404 error. Is there also have some config that i have not set ?

**Comment by viniciuschiele** [comment]
Have you initialized apidoc with Flask?

e.g:

```
app = Flask(__name__)
doc = ApiDoc(app)
```

**Comment by allran** [comment]
Yes, I have load it. but it only have one line code, there is not use in other place, is it right?

**Comment by viniciuschiele** [comment]
Only this line is enough to work, maybe your static folder is not in the right place.

You could debug and see which is the path Flask is trying to access.
This is the line your could check: https://github.com/viniciuschiele/flask-apidoc/blob/master/flask_apidoc/apidoc.py#L74

**Comment by allran** [comment]
Thank you @viniciuschiele , i have successfully read docs in html.

**Comment by WillZt** [comment]
I encounter the same problem, when i load 'http://localhost:5000/docs/', result 404 error. How to solve it? @viniciuschiele @allran

**Comment by RutujaWanjari** [comment]
I am also facing same problem issue.
