### ISSUE TITLE
WindowError: [Error 2]

### ISSUE THREAD

**Issue by wendingzhulu** [viniciuschiele/flask-apidoc#7]
Hello, I'm a new flask user
I can use 'apidoc -i src -o dest' command to generate apidocs, but failed to use 'python manage.py apidoc', the error list as follow:
`D:\DevelopSpace\pythons\apps\express_opt\opt-web>python manage.py apidoc
Traceback (most recent call last):
  File "manage.py", line 32, in <module>
    manager.run()
  File "D:\Program\Python27\lib\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "D:\Program\Python27\lib\site-packages\flask_script\__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "D:\Program\Python27\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "D:\Program\Python27\lib\site-packages\flask_apidoc\commands.py", line 43, in run
    return subprocess.call(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File "D:\Program\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "D:\Program\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\Program\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]
`

I don't know how to use flask to touch the URL 127.0.0.1:500/docs.

**Comment by viniciuschiele** [comment]
Usually it happens when apidoc wasn't found in your PC.

Could you install apidoc running this command:

```npm install apidoc -g```

**Comment by wendingzhulu** [comment]
Thanks for your reply.
I have installed the apidoc as the command `apidoc -i app/src -o docs` was found success.
